version: "3"

services:
  speedtest:
    image: python-speedtest:1.0
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
        - TIMEZONE=${TIMEZONE}
    network_mode: host

