version: "3"

services:
  speedtest:
    image: python-speedtest:1.0
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
        - TIMEZONE=${TIMEZONE}
